---
- name: Install base packages
  apt:
    name="{{item}}"
  with_items:
    # Needed for some Ansible apt module operations
    - "aptitude"

    # Other basic packages that may not be pre-installed on armhf or Debian
    - "cron"
    - "curl"
    - "less"
    - "rsync"
    - "tmux"
    - "ufw"
    - "vim"
