---
- name: "Setup repository key."
  apt_key:
    id="719D92DE0889A1CD"
    url="https://keybase.io/lp0/key.asc"
    keyring="/etc/apt/trusted.gpg.d/lpeltier.gpg"

- name: "Setup repository address."
  apt_repository:
    repo="deb http://leo-peltier.fr/packages xenial main"

- name: Install base package.
  apt:
    name="lpeltier-base"
