---
- name: Set hostname
  hostname: name="{{init_hostname}}"

- name: Replace hostname in hosts
  lineinfile:
    dest="/etc/hosts"
    regexp="^127\.0\.1\.1\t"
    line="127.0.1.1\t{{init_hostname}}"

- name: Disable UFW ipv6
  lineinfile:
    dest="/etc/default/ufw"
    regexp="^IPV6="
    line="IPV6=no"
  when:
    "init_disable_ufw_ipv6"

- name: Allow SSH through UFW
  ufw:
    rule="allow"
    name="OpenSSH"

- name: Open ports
  ufw:
    rule="allow"
    to_port="{{item.to_port}}"
    proto="{{item.proto}}"
  with_items:
    "{{init_ufw_open}}"

- name: Deny incoming connections by default
  ufw:
    state="enabled"
    policy="deny"
    direction="incoming"

- name: Set vim as default editor
  alternatives:
    name="editor"
    path="/usr/bin/vim.basic"

- name: Write files
  copy:
    content="{{item.content}}"
    dest="{{item.dest}}"
    owner="{{item.owner}}"
    group="{{item.group}}"
    mode="{{item.mode}}"
  with_items: "{{init_files}}"
